"""add group_id to messages

Revision ID: 06043e8dc563
Revises: a85be5b0590e
Create Date: 2026-05-17 16:54:04.538654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06043e8dc563'
down_revision: Union[str, Sequence[str], None] = 'a85be5b0590e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('group_id', sa.Integer(), nullable=True))
    op.alter_column('messages', 'dialog_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'messages', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.alter_column('messages', 'dialog_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('messages', 'group_id')
    # ### end Alembic commands ###
