"""add attachments to messages

Revision ID: 83e07428c7bd
Revises: 06043e8dc563
Create Date: 2026-05-18 18:26:53.533403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83e07428c7bd'
down_revision: Union[str, Sequence[str], None] = '06043e8dc563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('attachments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'attachments')
    # ### end Alembic commands ###
